# Generated by Django 4.2.16 on 2024-10-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESIEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(max_length=512)),
                ('method', models.TextField(max_length=32)),
                ('route', models.TextField(max_length=512)),
                ('tag', models.TextField(max_length=512)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ESITrackerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_between_checks', models.IntegerField(default=600)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ESIEndpointStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'RED'), (2, 'YELLOW'), (3, 'GREEN')])),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_tracker.esiendpoint')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
