# Generated by Django 4.2.16 on 2025-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esiendpointstatus',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
